### ISSUE TITLE
🚀 Release 1.7.0

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#104]
This issue tracks the status of the Shoppingfeed module release 1.7.0 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.7.0
Estimated beta | March 2022
Estimated release | March 2022

## Current status

- [x] Specification
    - [x] improvement: availability of a product send to Shopping Feed (32609)
    - [x] refactoring shipping pickup method
    - [x] refactoring hook ValidateOrder
- [x] Feature development
    - [x] quality: add github actions to check php lintner, cs fixer and phpstan #105 
    - [x] quality: import order unit testing (33313) #113
    - [x] improvement: add attribute with texture and hexa color of PrestaShop attribute "is color" (33141) #112 
    - [x] improvement: split firstname and lastname order import for _la redoute_ (31667) #121 
    - [x] bugfix: PHP 7.3 Warning PHP HP Warning:  "continue" targeting switch is equivalent to "break". (32616) #110 
    - [x] improvement: availability of a product send to Shopping Feed (32609) #123
    - refactoring shipping pickup method
    - [x] improvement: Import ID pickup to _COLIZEY_ (31868)
    - [x] bugfix: DPD relais PickUp (33412) #122 
    - refactoring hook ValidateOrder
    - [x] refactoring: validation order to prevent bad value send to ERP or notification email 32951 #115 
- [x] Translation
- [x] Stabilization
- [x] Build (Beta) - march 21
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
