### ISSUE TITLE
🚀 Release 1.7.1

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#124]
This issue tracks the status of the Shoppingfeed module release 1.7.1 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.7.1
Estimated beta | May 2022
Estimated release | May 2022

## Current status

- [x] Specification
- [x] Feature development
    - [x] fixbug: Zalando shipping is empty (34027) #133
    - [x] fixbug : unsupported currency (33971 & 34355) #137  
    - [x] refactoring: Relais Colis tracking number (31269) #134
    - [x] fixbug : import order already shipped by MarketPlace (34645) #141
    - [x] fixbug : import orders products with several taxes combined (34618) #140 
    - [x] fixbug : Map product reference (34668) #142
    - [x] fixbug : Get address email from shippingAddress if billingAdress email is not valid #146 
    - [x] Improvment : Add Manomanopro with DPD Relay (34351) #139 
- [x] Translation
- [x] Stabilization
- [x] Build (Beta) - march 22
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
