### ISSUE TITLE
🚀 Release 1.8.0

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#150]
This issue tracks the status of the Shoppingfeed module release 1.8.0 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.8.0
Estimated beta | June 2022
Estimated release | July 2022

## Current status

- [x] Specification
- [x] Feature development
    - [x] improvement: Create a product CDiscount fees (29621) #159 
    - [x] fixbug: Manage carriers deletion linked to Shoppingfeed (29565 / 31566) #158
    - [x] improvement: Import VAT Intracom from Amazon and ManoManoPro (32670 / 32582)  #157
    - [x] improvement: Add Etag Header on product feed (33121) #155
    - [x] fixbug: fix prices for orders splited by two shippments (33703) #156
    - [x] improvement: Disabled tickets in case of failed return (34100) #154
    - [x] improvement: colissimo relay on Manomano (34374) #153
    - [x] improvement: let configure email during Payment (34463) #152
    - [x] fixbug: Authorized "/" in lastname or firstname (34575) #151
    - [x] fixbug: Catch level "Throwable" in case of conflict with an other module (34786) #160
    - [x] Manage a default carrier for each marketplace if missing data (35398) #162 
- [x] Translation
- [x] Stabilization
- [x] Build (Beta) - June 22
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
