### ISSUE TITLE
🚀 Release 1.8.1

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#165]
This issue tracks the status of the Shoppingfeed module release 1.8.1 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.8.1
Estimated beta | July 2022
Estimated release | August 2022

## Current status

- [x] Specification
- [x] Feature development
    - [x] improvement: Support tab included on the module (34626) #168
    - [x] improvement: Add ecotax value on product's variations #176
    - [x] improvement: Mondial Relais for GoSport (35281) #175 
    - [x] improvement: Colissimo relay for Galerie Lafayette #180
    - [x] improvement: Add htaccess forbidden #184 
    - [x] bugfix: Set a default carrier for Manomano EPMM (35398) #170
    - [x] bugfix: Import error on pack if a reference has no stock (35685) #171 
    - [x] bugfix: Enabled ManomanoColissimo and MonechelleColissimo import rule (34374) #173
    - [x] bugfix: Update id_shop in the Context with the current token #174
    - [x] bugfix: Fix image order in product feed #178
    - [x] bugfix: Removing cart rules "gift" during order import proces #179
- [x] Translation
- [x] Stabilization
- [x] Build (Beta) - August 22
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
