### ISSUE TITLE
🚀 Release 1.9.0

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#212]
This issue tracks the status of the Shoppingfeed module release 1.9.1 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.9.0
Estimated beta | September 2022
Estimated release | September 2022

## Current status

- [x] Specification
- [x] Feature development
    - [x] Import already delivered order (35445) #187
    - [x] Insert in metadata of product feed module and php version (36040) #188
    - [x] Send orders taken on the PrestaShop (30199) #189
    - [x] Add module hidefeatures in potential conflict with product feed #200
    - [x] Manage addition fields for Zalando displayed on invoices (35450) #194
    - [x] Upgrade SDK shoppingfeed (35634) #191
    - [x] XML feed: fix selection of products (36151) #190
    - [x] Revert ecotax on variations #199
- [x] Translation
- [x] Stabilization
- [x] Build (Beta)
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
