### ISSUE TITLE
🚀 Release 1.9.1

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#213]
This issue tracks the status of the Shoppingfeed module release 1.9.1 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.9.1
Estimated beta | November 2022
Estimated release | November 2022

## Current status

- [x] Specification
- [x] Feature development
    - [x] bugfix: issue with Guzzle (new install of the module) 37153 #211
    - [x] bugfix: 36953 #207
    - [x] bugfix: regression translation mod on PS 1.6 #214
    - [x] improvement: Update logo shoppingfeed (37373) #217 
    - [x] improvement: catch warning during the order import in case of missing product translations (37365) #216 
    - [x] improvement: compatibility PS 8.0 #215 
    - [x] improvement: add CDiscount fee product not all times (36546) #218 
    - [x] improvement: Update rule AmazonEbay for Alltricks marketplace (36944) #219 #221
    - [x]  improvement: Add default phone mobile for order with colissimo (36642) #222 
    - [x] bugfix: Warnings during order import (37093) #223 
    - [x] Apply specific price on product feed (37092) #224
- [x] Translation
- [x] Stabilization
- [x] Build (Beta)
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
