### ISSUE TITLE
🚀 Release 1.9.2

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#233]
This issue tracks the status of the Shoppingfeed module release 1.9.2 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.9.2
Estimated beta | December 2022
Estimated release | December 2022

## Current status

- [x] Specification
- [x] Feature development
    - [x] Fixbug: remove a discount from invoice (37710) #227 
    - [x] Improvement: Add token as mandatory to get product xml feed (37103) #228 
    - [x] Improvement: Using token in addition to secure_key in cron (36176) #229 
    - [x] Improvement: Adding dni to address (37070) #230 
    - [x] Improvement: Handle the new field relayId on order import (37419) #231 
    - [x] Improvement: Add marketplace reference as payement transaction ID (37799) #234 
    - [x] Fixbug: order tracking (30199) #235 
    - [x]  Order shipped by marketplace imported in error (38044) #236 
- [x] Translation
- [x] Stabilization
- [x] Build (Beta)
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
