### ISSUE TITLE
🚀 Release 1.10.1

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#273]
This issue tracks the status of the Shoppingfeed module release 1.10.1 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.10.1
Estimated release | June 2023

## Current status

- [x] Specification
- [x] Feature development
    - [x] enhancement: Miravia orders split name (40197) #272
    - [x] enhancement: Update label shipped by marketplace (39547) #266
    - [x] bugfix: Products do not get to index (40131) #271
    - [x] bugfix: Error during xml feed creation (40129) #270
    - [x] bugfix: Eligibility condition for a rule Zalando (40613) #269
    - [x] bugfix: Product feed taking into account id_shop (40434) #268
    - [x] bugfix: xml tag has to locate at first line (40448) #267
    - [x] bugfix: Apply VAT on ecotax on the feed (39720) #264
    - [x] bugfix: acknowledge optimisation in case of errors (39720) #274
- [x] Translation
- [x] Stabilization
- [x] Build (Beta)
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
