### ISSUE TITLE
🚀 Release 1.10.2

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#280]
This issue tracks the status of the Shoppingfeed module release 1.10.1 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.10.2
Estimated release | July 2023

## Current status

- [x] Specification
- [x] Feature development
    - [x] bugfix: Selects categories in filters duplicate contents in multishop (40990) #276
    - [x] bugfix: Fix batch id empty #277 
    - [x] bugfix: pdf assign mass export (41053) #278 
    - [x] bugfix: CLI prevent image URL on with double schema #279
    - [x] bugfix: Added prefix to lib psr (41355) #281
    - [x] bugfix: Split name rule for laredoutemirakl (41125) #282
- [x] Translation
- [x] Stabilization
- [x] Build (Beta)
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
