### ISSUE TITLE
🚀 Release 1.10.3

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#290]
This issue tracks the status of the Shoppingfeed module release 1.10.3 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.10.3
Estimated release | Sept 2023

## Current status

- [x] Specification
- [x] Feature development
    - [x] bugfix: Update logs in case of sync stock (41463) #285 
    - [x] bugfix: Skip tax in case of Retif marketplace (41868) #286 
    - [x] improvment: ProductSerializer - add field 'min quantity for sale' (41039) #287 
    - [x] improvment: Adjust order importation date 30 rolling days (41653) #288 
    - [x] improvment: Add configuration for Test order not only canceled after import (40564) #289 
    - [x] bugfix: compatibility for PHP 5.6 - SfTools #291 by @Jeremie-Kiwik 
- [x] Translation
- [x] Stabilization
- [x] Build (Beta)
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
