### ISSUE TITLE
🚀 Release 1.10.4

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#299]
This issue tracks the status of the Shoppingfeed module release 1.10.4 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.10.4
Estimated release | Octobre 2023

## Current status

- [x] Specification
- [x] Feature development
    - [x] Fix multishop stock management (42371) #296
    - [x] Add warning shoppingfeed compatibility > prepare release 2.0.0 (42404) #295
    - [x] Update page register (42363) #297 
    - [x] Update field billing fiscal number for manomano (42285) #298 
    - [x] Fix GLS BC on latest release (42310) #303
    - [x] Fix shipping cost by weight for variations (42561) #301 
    - [x] Replace dots in firstname and lastname (42601) #302 
    - [x] Add new rule order import Leroy Merlin (42637) #304
- [x] Translation
- [x] Stabilization
- [x] Build (Beta)
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
