### ISSUE TITLE
 🚀 Release 1.10.6

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#321]
This issue tracks the status of the Shoppingfeed module release 1.10.5 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.10.6
Estimated release | January 2024

## Current status

- [x] Specification
- [x] Feature development
    - [x] Fix Mondial Relay SOAP client domain (43708) #320
    - [x] Add company name on colissimo address for ManoMano (43707) #319 
    - [x] Fix cleaning of old task order status sync (42833) #316
    - [x] Creation of the order-carrier association if it it's need (43219) #315 
    - [x] Update Header User-Agent for tracking (43218) #314 
    - [x] Add prefix on the namespace for guzzle Adapter (41355) #322 
- [x] Translation
- [x] Stabilization
- [x] Build (Beta)
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
