### ISSUE TITLE
🚀 Release 1.12.1

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#373]
This issue tracks the status of the Shoppingfeed module release 1.12.1 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.12.1
Estimated release | Oct 24

## Current status

- [x] Specification
- [x] Feature development
    - [x] Do not look for a point id if an order comes from eBay (48460) #372
    - [x] Add option in BO to enable/disable adding cdiscount fees (48305) #371
    - [x] SyncAll execution precess compat PS 8+ (48174) #368
    - [x] Add multiple features on product feeds (48163) #367
    - [x] Add rule customergroup (48153) #366 #370
    - [x] Generating a reference of the cdiscount fees according to the module configurations (47744) #363
    - [x] Set order explicitly on preloading product request (47756) #362
    - [x] Taking into account store while acknowledge an order (48068) #365
    - [x] Fix GLS _DB_PREFIX_ for PS 1.6 (47842) #361
    - [x] Wrong address parsing (47367) #357
    - [x] Warning during product indexing (47539) #358
    - [x] json_decode(): Passing null to parameter on product feed (47566) #359
    - [x] Little ergonomic / translation enhancements (47538) #360
- [x] Translation
- [x] Stabilization
- [x] Build (Beta)
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
