### ISSUE TITLE
🚀 Release 1.12.2

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#386]
This issue tracks the status of the Shoppingfeed module release 1.12.2 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.12.2
Estimated release | December 2024

## Current status

- [x] Specification
- [x] Feature development
    - [x] Allow removing the flow hierarchy (49175) #384
    - [x] Get ticket from a correct store (49015) #378
    - [x] Add supplier reference from dedicated table (49020) #377
    - [x] Wrong tax in product xml in multitoken multishop (48934) #379
    - [x] Relay point id in shippingAddress.other (48780) #376
- [x] Translation
- [x] Stabilization
- [x] Build (Beta)
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release

 BC:
* PrestaShop > 1.7.6 and PHP > 7.1
