### ISSUE TITLE
🚀 Release 1.4.1

### ISSUE THREAD

**Issue by clotaire202** [shoppingflux/module-prestashop#4]
This issue tracks the status of the shoppingfeed module for PrestaShop 1.4.1 release

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.4.1
Estimated beta | October 2020
Estimated release | November 2020

## Current status

- [x] Fix bugs
  - [x] Add import order rules: Let's choice an order status at the end of import process #25710
  - [x] Bug on product feed serializer: PrestaShop "reference" field doesn't appear on attribute named "mpn" as expected #25786
  - [x] Bug on product feed serializer: Discounts with specific prices not applied #25815
  - [x] Fix bug PS: 1.7.6+ > token assignation in case of multi-currency
  - [x] Fix bug PS: 1.6.0 > product feed serializer not completed due to nullable `actions` fields
  - [x] Fix bug > bad condition "inactive task" on Shoppingfeed products configuration admin tab #25848
  - [x] Fix bug on import order in case of multi token
  - [x] Fix brand name and link on the feed #25886
- [ ] Zip Available on 1.4.1 tag/release
