### ISSUE TITLE
🚀 Release 1.6.0

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#74]
This issue tracks the status of the Shoppingfeed module release 1.6.0 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.6.0
Estimated beta | December 2021
Estimated release | January 2022

## Current status

- [x] Specification
- [x] Feature development
  - [x] Fix bug : none active images sent in the products feed (#30585) #78
  - [x] Fix bug : hierararchy node error (#31448) #81
  - [x] Fix bug : Wrong domain in the product flow (#31908)  #79
  - [x] Fix bug : Discount not available for combination in a product xml flow (#32205) #80
  - [x] Improvement : Manage orders shipping imported from shoppingfluxexport module with on this module (#27965)  #73
  - [x] Improvement : Import orders Zalando - Colissimo point relais (#30781)  #71
  - [x] Improvement : Import orders Manomano - DPD Relais (#31085) #83
  - [x] Improvement : import order only recent order to not import old order not acknowleged (#26096)  #76 
  - [x] Improvement : add quiet mode for logs. do not save info level in quiet mode (#32121).
  - [x] Fix bug : wrong variations in product flow (#32496) #82
  - [x] Fix bug : order import failed (#29670) #75 
  - [x] Fix bug : lost products on feed (#32436)
  - [x] Improvement : ecotax, vat et weight > remove from product attribute, add on product node (#32336)
  - [x]  Fix bug : wrong price in catalog in case of multishop  #89 (32760)
- [x] Translation
- [x] Stabilization
- [x] Build (Beta) - Mid of December 21
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
