### ISSUE TITLE
🚀 Release 1.6.1

### ISSUE THREAD

**Issue by clotairer** [shoppingflux/module-prestashop#84]
This issue tracks the status of the Shoppingfeed module release 1.6.1 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 1.6.1
Estimated beta | January 2022
Estimated release | January 2022

## Current status

- [x] Specification
- [x] Feature development
  - [x] Improvement : best configuration of shipped orders (#29605 & #32121) #77
  - [x] Fix bug : if PrestaShop have a generic cart rules is not removed during  import orders (#32354) #92
  - [x] Fix bug : rounding the product indexing state to down (#32817)  #93
  - [x] Fix bug : price VAT exclude in case of multishop and specific tax rules (#32817 #32760)  #95
  - [x] Fix bug : remove SF order tickets status if in 404 error #94 
  - [x] Fix bug : invalid order state error (#32095) #96
  - [x] Fix bug : ManomanoDpdRelais. getting relay id (#31085)
  - [x] Fix bug :  PrestaShop 1.6.0 Translation method l not found in product front controller (#32989)
- [x] Translation
- [x] Stabilization
- [x] Build (Beta) - January 21
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
